export const product_mock_data = [
  { id: 1, productId: "Gelatine Leaves - Envelopes" },
  { id: 2, productId: "Nut - Hazelnut, Ground, Natural" },
  { id: 3, productId: "Beef - Diced" },
  { id: 4, productId: "Nantucket - Carrot Orange" },
  { id: 5, productId: "Sauce - Vodka Blush" },
  { id: 6, productId: "Wine - Red, Lurton Merlot De" },
  { id: 7, productId: "Cheese - Cheddar, Old White" },
  { id: 8, productId: "Coconut - Creamed, Pure" },
  { id: 9, productId: "Carbonated Water - Blackcherry" },
  { id: 10, productId: "Lemonade - Pineapple Passion" },
  { id: 11, productId: "Wine - Spumante Bambino White" },
  { id: 12, productId: "Pomello" },
  { id: 13, productId: "Juice - Apple, 500 Ml" },
  { id: 14, productId: "Lamb - Leg, Diced" },
  { id: 15, productId: "Wine - Vineland Estate Semi - Dry" },
  { id: 16, productId: "Wine - White, Antinore Orvieto" },
  { id: 17, productId: "Tea - Darjeeling, Azzura" },
  { id: 18, productId: "Pasta - Rotini, Dry" },
  { id: 19, productId: "Monkfish Fresh - Skin Off" },
  { id: 20, productId: "Muffin Chocolate Individual Wrap" },
  { id: 21, productId: "Spaghetti Squash" },
  { id: 22, productId: "Calypso - Lemonade" },
  { id: 23, productId: "Muffin - Mix - Creme Brule 15l" },
  { id: 24, productId: "Nougat - Paste / Cream" },
  { id: 25, productId: "Hot Choc Vending" },
  { id: 26, productId: "Vector Energy Bar" },
  { id: 27, productId: "Beer - Upper Canada Lager" },
  { id: 28, productId: "Sobe - Lizard Fuel" },
  { id: 29, productId: "Muffin Hinge - 211n" },
  { id: 30, productId: "Flower - Leather Leaf Fern" },
  { id: 31, productId: "Melon - Watermelon Yellow" },
  { id: 32, productId: "Pasta - Fusili Tri - Coloured" },
  { id: 33, productId: "Pork - Sausage Casing" },
  { id: 34, productId: "Beer - Sleemans Cream Ale" },
  { id: 35, productId: "Skirt - 29 Foot" },
  { id: 36, productId: "Tea - Darjeeling, Azzura" },
  { id: 37, productId: "Mousse - Passion Fruit" },
  { id: 38, productId: "Jam - Apricot" },
  { id: 39, productId: "Energy Drink - Franks Original" },
  { id: 40, productId: "Lettuce - Mini Greens, Whole" },
  { id: 41, productId: "Star Fruit" },
  { id: 42, productId: "Soy Protein" },
  { id: 43, productId: "Poppy Seed" },
  { id: 44, productId: "Soup - Knorr, Chicken Gumbo" },
  { id: 45, productId: "Doilies - 7, Paper" },
  { id: 46, productId: "Onion - Dried" },
  { id: 47, productId: "Wine - Sogrape Mateus Rose" },
  { id: 48, productId: "Crab - Claws, 26 - 30" },
  { id: 49, productId: "Cookies - Oreo, 4 Pack" },
  { id: 50, productId: "Plasticforkblack" },
];
