<<<<<<< HEAD
import Navbar from "@/components/header/Navbar";
import Footer from "@/app/(app)/home/_components/Footer";

export default function AppLayout({
=======
import type { Metadata } from "next";
import "../globals.css";
import Providers from "@/providers/Providers";
import Navbar from "@/components/header/Navbar";
import { cn } from "@/lib/utils";
import { Poppins } from "@/styles/fonts";
import Footer from "./home/_components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
>>>>>>> 50726e06b949c3eb942f138757c3f4c24b51fe01
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <main>
      {/* @ts-expect-error Server Component */}
      <Navbar />
      {children}
      <Footer />
    </main>
=======
    <html lang="en" className="bg-slate-50">
      <body className={cn(Poppins.variable)}>
        <Providers>
          {/* @ts-expect-error Server Component */}
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
>>>>>>> 50726e06b949c3eb942f138757c3f4c24b51fe01
  );
}
