import type { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main lang="en" className="bg-slate-50">
      {children}
    </main>
  );
}
