import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers/Providers";
import { cn } from "@/lib/utils";
import { Poppins } from "@/styles/fonts";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-50">
      {" "}
      <script
        type="text/javascript"
        src="//pl23684301.highrevenuenetwork.com/ce/5e/1b/ce5e1be1e1f76ad4d4d04f84beea03b4.js"
      ></script>
      <body className={cn(Poppins.variable)}>
        <Providers>{children}</Providers>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
